<?php

$arTimezones=array(
	'Europe/Amsterdam'=>array(
		'active'=>0,
		'title'=>'Европа/Амстердам'
	),
	'Europe/Andorra'=>array(
		'active'=>0,
		'title'=>'Европа/Андорра'
	),
	'Europe/Athens'=>array(
		'active'=>0,
		'title'=>'Европа/Афины'
	),
	'Europe/Belfast'=>array(
		'active'=>0,
		'title'=>'Европа/Белфаст'
	),
	'Europe/Belgrade'=>array(
		'active'=>0,
		'title'=>'Европа/Белград'
	),
	'Europe/Berlin'=>array(
		'active'=>0,
		'title'=>'Европа/Берлин'
	),
	'Europe/Bratislava'=>array(
		'active'=>0,
		'title'=>'Европа/Братислава'
	),
	'Europe/Brussels'=>array(
		'active'=>0,
		'title'=>'Европа/Брюссель'
	),
	'Europe/Bucharest'=>array(
		'active'=>0,
		'title'=>'Европа/Бухарест'
	),
	'Europe/Budapest'=>array(
		'active'=>0,
		'title'=>'Европа/Будапешт'
	),
	'Europe/Chisinau'=>array(
		'active'=>0,
		'title'=>'Европа/Кишинёв'
	),
	'Europe/Copenhagen'=>array(
		'active'=>0,
		'title'=>'Европа/Копенгаген'
	),
	'Europe/Dublin'=>array(
		'active'=>0,
		'title'=>'Европа/Дублин'
	),
	'Europe/Gibraltar'=>array(
		'active'=>0,
		'title'=>'Европа/Гибралтар'
	),
	'Europe/Guernsey'=>array(
		'active'=>0,
		'title'=>'Европа/Гернси'
	),
	'Europe/Helsinki'=>array(
		'active'=>1,
		'title'=>'Европа/Хельсинки'
	),
	'Europe/Isle_of_Man'=>array(
		'active'=>0,
		'title'=>'Европа/Острова Мэн'
	),
	'Europe/Istanbul'=>array(
		'active'=>1,
		'title'=>'Европа/Стамбул'
	),
	'Europe/Jersey'=>array(
		'active'=>0,
		'title'=>'Европа/остров Джерси'
	),
	'Europe/Kaliningrad'=>array(
		'active'=>1,
		'title'=>'Европа/Калининград'
	),
	'Europe/Kiev'=>array(
		'active'=>0,
		'title'=>'Европа/Киев'
	),
	'Europe/Lisbon'=>array(
		'active'=>0,
		'title'=>'Европа/Лисcабон'
	),
	'Europe/Ljubljana'=>array(
		'active'=>0,
		'title'=>'Европа/Амстердам'
	),
	'Europe/London'=>array(
		'active'=>0,
		'title'=>'Европа/Амстердам'
	),
	'Europe/Luxembourg'=>array(
		'active'=>0,
		'title'=>'Европа/Амстердам'
	),
	'Europe/Madrid'=>array(
		'active'=>0,
		'title'=>'Европа/Амстердам'
	),
	'Europe/Malta'=>array(
		'active'=>0,
		'title'=>'Европа/Амстердам'
	),
	'Europe/Mariehamn'=>array(
		'active'=>0,
		'title'=>'Европа/Амстердам'
	),
	'Europe/Minsk'=>array(
		'active'=>0,
		'title'=>'Европа/Амстердам'
	),
	'Europe/Monaco'=>array(
		'active'=>0,
		'title'=>'Европа/Амстердам'
	),
	'Europe/Moscow'=>array(
		'active'=>0,
		'title'=>'Европа/Амстердам'
	),
	'Europe/Nicosia'=>array(
		'active'=>0,
		'title'=>'Европа/Амстердам'
	),
	'Europe/Oslo'=>array(
		'active'=>0,
		'title'=>'Европа/Амстердам'
	),
	'Europe/Paris'=>array(
		'active'=>0,
		'title'=>'Европа/Амстердам'
	),
	'Europe/Podgorica'=>array(
		'active'=>0,
		'title'=>'Европа/Амстердам'
	),
	'Europe/Prague'=>array(
		'active'=>0,
		'title'=>'Европа/Амстердам'
	),
	'Europe/Riga'=>array(
		'active'=>0,
		'title'=>'Европа/Амстердам'
	),
	'Europe/Rome'=>array(
		'active'=>0,
		'title'=>'Европа/Амстердам'
	),
	'Europe/Samara'=>array(
		'active'=>0,
		'title'=>'Европа/Амстердам'
	),
	'Europe/San_Marino'=>array(
		'active'=>0,
		'title'=>'Европа/Амстердам'
	),
	'Europe/Sarajevo'=>array(
		'active'=>0,
		'title'=>'Европа/Амстердам'
	),
	'Europe/Simferopol'=>array(
		'active'=>0,
		'title'=>'Европа/Амстердам'
	),
	'Europe/Skopje'=>array(
		'active'=>0,
		'title'=>'Европа/Амстердам'
	),
	'Europe/Sofia'=>array(
		'active'=>0,
		'title'=>'Европа/Амстердам'
	),
	'Europe/Stockholm'=>array(
		'active'=>0,
		'title'=>'Европа/Амстердам'
	),
	'Europe/Tallinn'=>array(
		'active'=>0,
		'title'=>'Европа/Амстердам'
	),
	'Europe/Tirane'=>array(
		'active'=>0,
		'title'=>'Европа/Амстердам'
	),
	'Europe/Tiraspol'=>array(
		'active'=>0,
		'title'=>'Европа/Амстердам'
	),
	'Europe/Uzhgorod'=>array(
		'active'=>0,
		'title'=>'Европа/Амстердам'
	),
	'Europe/Vaduz'=>array(
		'active'=>0,
		'title'=>'Европа/Амстердам'
	),
	'Europe/Vatican'=>array(
		'active'=>0,
		'title'=>'Европа/Амстердам'
	),
	'Europe/Vienna'=>array(
		'active'=>0,
		'title'=>'Европа/Амстердам'
	),
	'Europe/Vilnius'=>array(
		'active'=>0,
		'title'=>'Европа/Амстердам'
	),
	'Europe/Volgograd'=>array(
		'active'=>0,
		'title'=>'Европа/Амстердам'
	),
	'Europe/Warsaw'=>array(
		'active'=>0,
		'title'=>'Европа/Амстердам'
	),
	'Europe/Zagreb'=>array(
		'active'=>0,
		'title'=>'Европа/Амстердам'
	),
	'Europe/Zaporozhye'=>array(
		'active'=>0,
		'title'=>'Европа/Амстердам'
	),
	'Europe/Zurich'=>array(
		'active'=>0,
		'title'=>'Европа/Амстердам'
	),
	'Asia/Aden'=>array(
		'active'=>0,
		'title'=>'Европа/Амстердам'
	),
	'Asia/Almaty'=>array(
		'active'=>0,
		'title'=>'Европа/Амстердам'
	),
	'Asia/Amman'=>array(
		'active'=>0,
		'title'=>'Европа/Амстердам'
	),
	'Asia/Anadyr'=>array(
		'active'=>0,
		'title'=>'Европа/Амстердам'
	),
	'Asia/Aqtau'=>array(
		'active'=>0,
		'title'=>'Европа/Амстердам'
	),
	'Asia/Aqtobe'=>array(
		'active'=>0,
		'title'=>'Европа/Амстердам'
	),
	'Asia/Ashgabat'=>array(
		'active'=>0,
		'title'=>'Европа/Амстердам'
	),
	'Asia/Ashkhabad'=>array(
		'active'=>0,
		'title'=>'Европа/Амстердам'
	),
	'Asia/Baghdad'=>array(
		'active'=>0,
		'title'=>'Европа/Амстердам'
	),
	'Asia/Bahrain'=>array(
		'active'=>0,
		'title'=>'Европа/Амстердам'
	),
	'Asia/Baku'=>array(
		'active'=>0,
		'title'=>'Европа/Амстердам'
	),
	'Asia/Bangkok'=>array(
		'active'=>0,
		'title'=>'Европа/Амстердам'
	),
	'Asia/Beirut'=>array(
		'active'=>0,
		'title'=>'Европа/Амстердам'
	),
	'Asia/Bishkek'=>array(
		'active'=>0,
		'title'=>'Европа/Амстердам'
	),
	'Asia/Brunei'=>array(
		'active'=>0,
		'title'=>'Европа/Амстердам'
	),
	'Asia/Calcutta'=>array(
		'active'=>0,
		'title'=>'Европа/Амстердам'
	),
	'Asia/Choibalsan'=>array(
		'active'=>0,
		'title'=>'Европа/Амстердам'
	),
	'Asia/Chongqing'=>array(
		'active'=>0,
		'title'=>'Европа/Амстердам'
	),
	'Asia/Chungking'=>array(
		'active'=>0,
		'title'=>'Европа/Амстердам'
	),
	'Asia/Colombo'=>array(
		'active'=>0,
		'title'=>'Европа/Амстердам'
	),
	'Asia/Dacca'=>array(
		'active'=>0,
		'title'=>'Европа/Амстердам'
	),
	'Asia/Damascus'=>array(
		'active'=>0,
		'title'=>'Европа/Амстердам'
	),
	'Asia/Dhaka'=>array(
		'active'=>0,
		'title'=>'Европа/Амстердам'
	),
	'Asia/Dili'=>array(
		'active'=>0,
		'title'=>'Европа/Амстердам'
	),
	'Asia/Dubai'=>array(
		'active'=>0,
		'title'=>'Европа/Амстердам'
	),
	'Asia/Dushanbe'=>array(
		'active'=>0,
		'title'=>'Европа/Амстердам'
	),
	'Asia/Gaza'=>array(
		'active'=>0,
		'title'=>'Европа/Амстердам'
	),
	'Asia/Harbin'=>array(
		'active'=>0,
		'title'=>'Европа/Амстердам'
	),
	'Asia/Ho_Chi_Minh'=>array(
		'active'=>0,
		'title'=>'Европа/Амстердам'
	),
	'Asia/Hong_Kong'=>array(
		'active'=>0,
		'title'=>'Европа/Амстердам'
	),
	'Asia/Hovd'=>array(
		'active'=>0,
		'title'=>'Европа/Амстердам'
	),
	'Asia/Irkutsk'=>array(
		'active'=>0,
		'title'=>'Европа/Амстердам'
	),
	'Asia/Istanbul'=>array(
		'active'=>0,
		'title'=>'Европа/Амстердам'
	),
	'Asia/Jakarta'=>array(
		'active'=>0,
		'title'=>'Европа/Амстердам'
	),
	'Asia/Jayapura'=>array(
		'active'=>0,
		'title'=>'Европа/Амстердам'
	),
	'Asia/Jerusalem'=>array(
		'active'=>0,
		'title'=>'Европа/Амстердам'
	),
	'Asia/Kabul'=>array(
		'active'=>0,
		'title'=>'Европа/Амстердам'
	),
	'Asia/Kamchatka'=>array(
		'active'=>0,
		'title'=>'Европа/Амстердам'
	),
	'Asia/Karachi'=>array(
		'active'=>0,
		'title'=>'Европа/Амстердам'
	),
	'Asia/Kashgar'=>array(
		'active'=>0,
		'title'=>'Европа/Амстердам'
	),
	'Asia/Kathmandu'=>array(
		'active'=>0,
		'title'=>'Европа/Амстердам'
	),
	'Asia/Katmandu'=>array(
		'active'=>0,
		'title'=>'Европа/Амстердам'
	),
	'Asia/Kolkata'=>array(
		'active'=>0,
		'title'=>'Европа/Амстердам'
	),
	'Asia/Krasnoyarsk'=>array(
		'active'=>0,
		'title'=>'Европа/Амстердам'
	),
	'Asia/Kuala_Lumpur'=>array(
		'active'=>0,
		'title'=>'Европа/Амстердам'
	),
	'Asia/Kuching'=>array(
		'active'=>0,
		'title'=>'Европа/Амстердам'
	),
	'Asia/Kuwait'=>array(
		'active'=>0,
		'title'=>'Европа/Амстердам'
	),
	'Asia/Macao'=>array(
		'active'=>0,
		'title'=>'Европа/Амстердам'
	),
	'Asia/Macau'=>array(
		'active'=>0,
		'title'=>'Европа/Амстердам'
	),
	'Asia/Magadan'=>array(
		'active'=>0,
		'title'=>'Европа/Амстердам'
	),
	'Asia/Makassar'=>array(
		'active'=>0,
		'title'=>'Европа/Амстердам'
	),
	'Asia/Manila'=>array(
		'active'=>0,
		'title'=>'Европа/Амстердам'
	),
	'Asia/Muscat'=>array(
		'active'=>0,
		'title'=>'Европа/Амстердам'
	),
	'Asia/Nicosia'=>array(
		'active'=>0,
		'title'=>'Европа/Амстердам'
	),
	'Asia/Novokuznetsk'=>array(
		'active'=>0,
		'title'=>'Европа/Амстердам'
	),
	'Asia/Novosibirsk'=>array(
		'active'=>0,
		'title'=>'Европа/Амстердам'
	),
	'Asia/Omsk'=>array(
		'active'=>0,
		'title'=>'Европа/Амстердам'
	),
	'Asia/Oral'=>array(
		'active'=>0,
		'title'=>'Европа/Амстердам'
	),
	'Asia/Phnom_Penh'=>array(
		'active'=>0,
		'title'=>'Европа/Амстердам'
	),
	'Asia/Pontianak'=>array(
		'active'=>0,
		'title'=>'Европа/Амстердам'
	),
	'Asia/Pyongyang'=>array(
		'active'=>0,
		'title'=>'Европа/Амстердам'
	),
	'Asia/Qatar'=>array(
		'active'=>0,
		'title'=>'Европа/Амстердам'
	),
	'Asia/Qyzylorda'=>array(
		'active'=>0,
		'title'=>'Европа/Амстердам'
	),
	'Asia/Rangoon'=>array(
		'active'=>0,
		'title'=>'Европа/Амстердам'
	),
	'Asia/Riyadh'=>array(
		'active'=>0,
		'title'=>'Европа/Амстердам'
	),
	'Asia/Saigon'=>array(
		'active'=>0,
		'title'=>'Европа/Амстердам'
	),
	'Asia/Sakhalin'=>array(
		'active'=>0,
		'title'=>'Европа/Амстердам'
	),
	'Asia/Samarkand'=>array(
		'active'=>0,
		'title'=>'Европа/Амстердам'
	),
	'Asia/Seoul'=>array(
		'active'=>0,
		'title'=>'Европа/Амстердам'
	),
	'Asia/Shanghai'=>array(
		'active'=>0,
		'title'=>'Европа/Амстердам'
	),
	'Asia/Singapore'=>array(
		'active'=>0,
		'title'=>'Европа/Амстердам'
	),
	'Asia/Taipei'=>array(
		'active'=>0,
		'title'=>'Европа/Амстердам'
	),
	'Asia/Tashkent'=>array(
		'active'=>0,
		'title'=>'Европа/Амстердам'
	),
	'Asia/Tbilisi'=>array(
		'active'=>0,
		'title'=>'Европа/Амстердам'
	),
	'Asia/Tehran'=>array(
		'active'=>0,
		'title'=>'Европа/Амстердам'
	),
	'Asia/Tel_Aviv'=>array(
		'active'=>0,
		'title'=>'Европа/Амстердам'
	),
	'Asia/Thimbu'=>array(
		'active'=>0,
		'title'=>'Европа/Амстердам'
	),
	'Asia/Thimphu'=>array(
		'active'=>0,
		'title'=>'Европа/Амстердам'
	),
	'Asia/Tokyo'=>array(
		'active'=>0,
		'title'=>'Европа/Амстердам'
	),
	'Asia/Ujung_Pandang'=>array(
		'active'=>0,
		'title'=>'Европа/Амстердам'
	),
	'Asia/Ulaanbaatar'=>array(
		'active'=>0,
		'title'=>'Европа/Амстердам'
	),
	'Asia/Ulan_Bator'=>array(
		'active'=>0,
		'title'=>'Европа/Амстердам'
	),
	'Asia/Urumqi'=>array(
		'active'=>0,
		'title'=>'Европа/Амстердам'
	),
	'Asia/Vientiane'=>array(
		'active'=>0,
		'title'=>'Европа/Амстердам'
	),
	'Asia/Vladivostok'=>array(
		'active'=>0,
		'title'=>'Европа/Амстердам'
	),
	'Asia/Yakutsk'=>array(
		'active'=>0,
		'title'=>'Европа/Амстердам'
	),
	'Asia/Yekaterinburg'=>array(
		'active'=>0,
		'title'=>'Европа/Амстердам'
	),
	'Asia/Yerevan'=>array(
		'active'=>0,
		'title'=>'Европа/Амстердам'
	),
);
